name: Docker build

on:
  workflow_call:

permissions:
  contents: read

jobs:
  docker-build:
    name: Docker build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Build Docker image
        run: |
          set -a
          . ./versions.env
          set +a
          docker build --build-arg RELEASE_PHP --build-arg RELEASE_NODE --build-arg RELEASE_OPENTELEMETRY .
